name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts rpm sqlite3 libsqlite3-dev golang-1.21

      - name: Set version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')" >> $GITHUB_ENV

      - name: Build RPM package
        run: |
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          tar czf ~/rpmbuild/SOURCES/go-ollama-api-${VERSION}.tar.gz .
          rpmbuild -ba \
            --define "_version ${VERSION}" \
            --define "_commit_hash ${COMMIT_HASH}" \
            --define "_build_time ${BUILD_TIME}" \
            packaging/rpm/go-ollama-api.spec

      - name: Build DEB package
        run: |
          VERSION=${VERSION} COMMIT_HASH=${COMMIT_HASH} BUILD_TIME=${BUILD_TIME} dpkg-buildpackage -us -uc
          mkdir -p dist
          cp ../go-ollama-api_${VERSION}_*.deb dist/
          cp ~/rpmbuild/RPMS/x86_64/go-ollama-api-${VERSION}*.rpm dist/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.deb
            dist/*.rpm
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
